### ISSUE TITLE
 Failed to execute goal on project utility-belt

### ISSUE THREAD

**Issue by maireadmccabe** [confluentinc/common#98]
Cannot build of master, getting the below error
`Could not resolve dependencies for project io.confluent:utility-belt:jar:4.1.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.kafka:kafka_2.11:jar:1.1.0-SNAPSHOT, org.apache.kafka:kafka-clients:jar:1.1.0-SNAPSHOT, org.apache.kafka:kafka-clients:jar:test:1.1.0-SNAPSHOT, org.apache.kafka:kafka_2.11:jar:test:1.1.0-SNAPSHOT: Failure to find org.apache.kafka:kafka_2.11:jar:1.1.0-SNAPSHOT in http://packages.confluent.io/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced`

**Comment by ewencp** [comment]
@maireadmccabe This is from a different repo, but the same applies: https://github.com/confluentinc/schema-registry/wiki/FAQ#when-i-try-to-compile-i-get-an-error-about-a-missing-snapshot-dependency You would need to build/install Kafka before building this repository. This is a relatively new requirement for this repo due to some reorganization wrt how we're handling docker images.

**Comment by JollyNg** [comment]
kafka can be installed successfully. However, rest-utils cannot be build. The errors are as following. Please help!

#> mvn clean install
[INFO] Scanning for projects...
[WARNING] Could not transfer metadata io.confluent:common:4.1.0-SNAPSHOT/maven-metadata.xml from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.confluent:rest-utils-parent:[unknown-version]: Could not transfer artifact io.confluent:common:pom:4.1.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 8, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.confluent:rest-utils-parent:[unknown-version] (/rest-utils-master/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent:rest-utils-parent:[unknown-version]: Could not transfer artifact io.confluent:common:pom:4.1.0-SNAPSHOT from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 8, column 13: Cannot access ${confluent.maven.repo} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by sreenivasulun** [comment]
Mee too getting same as @maireadmccabe . Could anybody help me?

**Comment by awartika** [comment]
I tried to install kafka but could not build it.  There is no grade wrapper.

**Comment by ewencp** [comment]
@JollyNg @sreenivasulun The dependencies for rest-utils are Kafka, then confluentinc/common, then rest-utils. Build these in that order and you should be good.

@awartika That's probably better addressed in the Kafka community than here, but the omission of the gradle wrapper has to do with binaries in source releases iirc -- the source releases are just snapshots of the repo and are not supposed to include any binary bits, so checking in gradlew causes problems. You can just run `gradle` first in the Kafka directory to setup the gradle wrapper, then everything else should just work (assuming you have a recent enough version of gradle installed).

**Comment by sankarav** [comment]
Incase you facing the same problem again do the following,

`
git clone https://github.com/apache/kafka.git
gradle wrapper (assuming you have gradle installed already)
./gradlew installAll
`

`
git clone https://github.com/confluentinc/common.git
mvn clean install
`
`
git clone https://github.com/confluentinc/rest-utils.git
mvn clean install
`
`
git clone https://github.com/confluentinc/schema-registry.git
mvn clean install
`
`
git clone https://github.com/confluentinc/kafka-rest.git
mvn clean install
`

**Comment by awartika** [comment]
@sankarav thank you. Yes I am still unable to build this. Which version of cradle is required ?

**Comment by JollyNg** [comment]
@ewencp I m still failed to install the "common" and "rest-utils". As you advised, the steps should be the same as what @sankara was listed.
However, I cannot install "common" with "mvn clean install" successfully. The error codes are as below.

[ERROR] Failed to execute goal on project utility-belt: Could not resolve dependencies for project io.confluent:utility-belt:jar:4.1.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.kafka:kafka_2.11:jar:1.1.0-SNAPSHOT, org.apache.kafka:kafka-clients:jar:1.1.0-SNAPSHOT, org.apache.kafka:kafka-clients:jar:test:1.1.0-SNAPSHOT, org.apache.kafka:kafka_2.11:jar:test:1.1.0-SNAPSHOT: Failure to find org.apache.kafka:kafka_2.11:jar:1.1.0-SNAPSHOT in http://packages.confluent.io/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced

**Comment by ewencp** [comment]
The missing artifact is a SNAPSHOT artifact from Kafka-- the sequence of
builds/installations is Kafka, common, rest-utils. You would need to start
by building Kafka from the 1.1 branch and run a `./gradlew install`. Note
that you specifically need the *1.1* branch/version of Kafka. You can't
just grab trunk.

I don't have a specific timeframe yet, but we're planning to work on making
a public snapshot repository of Kafka and Confluent Platform artifacts
available publicly and integration them into these builds so you won't get
stuck on issues like this in the future -- the needed dependencies would
just be pulled from the SNAPSHOT repository automatically, based on configs
included in the Maven build.

-Ewen

**Comment by JollyNg** [comment]
Thanks @ewencp !
I have installed the components successfully. The version/branch and install sequence are listed below.
kafka-1.1, common-4.1.x, rest-utils-4.1.x, schema-registry-4.1.x and kafka-rest-4.1.x

**Comment by jixinhe111** [comment]
@ewencp 
I failed during the `./gradlew installAll` of Kafka cloned from github(https://github.com/apache/kafka/)
but I get:
`Could not determine the dependencies of task ':kafka:clients:compileTestJava'.`
`Could not create service of type AnnotationProcessorDetector using JavaGradleScopeServices.createAnnotationProcessorDetector().`
can you please help me sovle it!

**Comment by tstuber** [comment]
@ewencp thanks for the summary, that finally also worked for me. I used the following steps (a bit in more detail) to build it. Actually our company network (proxy and maven repo) was a problem since could either resolve dependencies or run the integration tests. Therefore, I had to skip the tests. 

```
git clone --branch 1.1.0 https://github.com/apache/kafka.git
gradle wrapper
./gradlew installAll

git clone https://github.com/confluentinc/common.git
git checkout origin/4.1.x
mvn clean install -Dmaven.test.skip=true

git clone https://github.com/confluentinc/rest-utils.git
git checkout origin/4.1.x
mvn clean install -Dmaven.test.skip=true

git clone https://github.com/confluentinc/schema-registry.git
git checkout origin/4.1.x
mvn clean install -Dmaven.test.skip=true

git clone https://github.com/confluentinc/kafka-rest.git
git checkout origin/4.1.x
mvn clean install -Dmaven.test.skip=true
```
